Website/index.html
Website/style.css

First Version

---

.gitignore
Extension/background.js
Extension/manifest.json
Extension/popup.html
Extension/popup.js
Extension/stylesheets/stylesheet.css

Displayed badge score.
Added score adjustment for BCorp and BlueSign companies.
Adjusted visuals within popup (badges).
Changed manifest.json to version 0.2

Visual popup update

---

Backend/src/main/java/com/example/appengine/springboot/SpringbootApplication.java

Makes name comparison case insensitive in backend.
cuts off name returned by bigpicture API to one word in order to produce a valid url

minor improvements to name recognition

---

Extension/background.js
Extension/popup.html
Extension/popup.js
Extension/stylesheets/stylesheet.css

Fixed NaN rating error on some pages.
Changed a shop rating of "0" to display "Shop Rating Unavailable" for page.
Changed badges to match.
Changed message styling color to make it seem like more of an alert.

Fixed NaN rating error and changed styling

---

Backend/src/main/java/com/example/appengine/springboot/Business.java
Backend/src/main/java/com/example/appengine/springboot/SpringbootApplication.java

-Reorganized code for clarity
-Added .update() method to Business class so that data can be updated without loss of previous info
-Added comments

added masterController, .update(), comments

---

Extension/popup.js

fixes bluesign score +1 error

---

Extension/manifest.json

This is the stupidest bug fix and it took Linda and I several hours of debugging and testing.

Newtabs now display the proper popup. 

---

Extension/popup.html

Linked "View Details" button to http://www.ethicli.com/

Linked "View Details" button

---

Extension/popup.html
Extension/stylesheets/stylesheet.css

BLM and Black-Owned Business badges added. Adjusted badge padding. Tooltips (text that shows on hover) also added.

Added BLM badges with tooltips

---

Website-and-Backend/src/main/resources/public/index.html
Website-and-Backend/src/main/resources/public/stylescripts/script.js
Website-and-Backend/src/main/resources/public/stylescripts/style.css

Made menu clickable
adjusted article text
Added SEO keywords

Made menu clickable, adjusted articles

---

Website-and-Backend/src/main/java/com/example/appengine/springboot/Business.java
Website-and-Backend/src/main/java/com/example/appengine/springboot/SpringbootApplication.java
Website-and-Backend/src/main/resources/Black-Owned Businesses-Black-Owned Online Businesses.csv
Website-and-Backend/src/main/resources/Financial Contributions-Companies Supporting Black Lives.csv

Added BLM and Black-Owned Business Source Data.
Added new variables to Business.java
Added searches for new data to SpringbootApplication.java

Add blm data

---

Website-and-Backend/src/main/java/com/example/appengine/springboot/Business.java
Website-and-Backend/src/main/java/com/example/appengine/springboot/SpringbootApplication.java
Website-and-Backend/src/main/resources/Black-Owned Businesses-Black-Owned Online Businesses.csv
Website-and-Backend/src/main/resources/bcorp.csv

Built Generic Data Source Reader: Passes the datasource filename, the searchTerm, the number of columns in the datasource, and the order in which their columns are to be read. The columns that are not present are given a -1 value so that the reader passes over them. 
Added a specific contribution variable to the Business class
Removed the column labels from bcorp.csv
Added a url to black owned business data

Built Generic Data Source Reader

---

Website-and-Backend/src/main/resources/public/index.html
Website-and-Backend/src/main/resources/public/stylescripts/style.css

Updated Medium Article

---

Website-and-Backend/src/main/java/com/example/appengine/springboot/SpringbootApplication.java

- So first of all.. I misspelled column like 80 times so I fixed that.. sorry..
- I made the compare function much more robust. The new algorithm works as follows: 
1) Checks to see if the searchTerm and website is an exact match so that we don't get issues (eg. 'amazon' != 'amazonia' and 'gap' !=  'gape')
2) If there is no website match (or website) it checks to see it the searchTerm i an exact match with one of the business.name words (eg. 'prAna' == 'prAna Living')
3) If there is still no match, it checks to see if there are two word combos that it will match with (eg. 'homedepot' == 'Home Depot')
4) If there is still no match, it checks to see if there are three word combos that it will match with (eg. 'llbean' == 'L. L. Bean')
-Additionally the compare pulls all unnecessary …

improved compare algorithm and fixed column misspelling

---

Extension/background.js
Extension/popup.js

Properly retrieves manual ratings

Fix rating

---

Extension/background.js
Extension/content.js

Fixes bug #109

---

Extension/background.js
Extension/content.js

Blacklisted search engines ["google", "bing", "yahoo",  "baidu", "aol", "duckduckgo", "yandex", "ecosia"]
Have yet to block main pages of social media (feeds)

Blacklist search engines and socials

---

Extension/background.js
Extension/popupNoRating.html

Added badge links to data.world
Changed badge score to rounded number

Added badge links

---

Extension/background.js
Extension/popup.html
Extension/popupNoRating.html

Added target_blank to links and updated popup.html with badge links

Fix badge link

---

Extension/background.js

Switched to var url = 'http://shop-ethicli.wl.r.appspot.com/score/' + companyName;

Change api call url

---

Extension/popup.html
Extension/popup.js
Extension/stylesheets/stylesheet.css

Updated scores to reflect backend data! IT WORKS HOLY MOLY!!
Amazon
Walmart
Walgreens
Costco

Updated scores to reflect backend data!

---

Website-and-Backend/src/main/resources/public/stylescripts/script.js
Website-and-Backend/src/main/resources/public/stylescripts/style.css

Hid "In the News" section

---

Extension/manifest.json
Extension/popup.html
Extension/popup.js
Extension/popupNoRating.html
Extension/popupNotShop.html
Extension/stylesheets/stylesheet.css

Added emailing button to "Something Looks Wrong"
Changed and added some styling
Changed CSS formatting
On hover
In New Tab:

Added emailing button to "Shomething Looks Wrong"

---

Extension/background.js

Removes reliance on bigpicture api. This should increase the rate at which we properly identify name matches

Name matching bug fix

---

Website-and-Backend/src/main/resources/public/faq.html
Website-and-Backend/src/main/resources/public/index.html
Website-and-Backend/src/main/resources/public/privacy.html
Website-and-Backend/src/main/resources/public/stylescripts/style.css

Added and linked FAQ page to Website

Added and linked FAQ page

---

Website-and-Backend/src/main/resources/public/404.html
Website-and-Backend/src/main/resources/public/faq.html
Website-and-Backend/src/main/resources/public/index.html
Website-and-Backend/src/main/resources/public/privacy.html

Geotag from: https://analytics.google.com/analytics/web/?authuser=3#/a173025073w240462838p224406614/admin/tracking/tracking-code/
The analytics won't work until the site is deployed again.

Added Analytics

---

Website-and-Backend/src/main/java/com/example/appengine/springboot/SpringbootApplication.java

- Added 'HttpServletResponse response' to arguments. It is essential to do as an argument rather than a local variable because you cannot make a null HttpServletResponse and giving it non null arguments would be erroneous. Also i think it has something to do with the connectivity in the response.
- Added header 'response.addHeader("Access-Control-Allow-Origin", "*");'' This should tell Firefox that Access-Control-Allow-Origin is given to everybody.

header added

---

Extension/popup.js

Hid tooltip when no subscores available,
Fixed some code formatting
Hovered on a page with subscores:
Hovered on a page with no subscores:

Hid tooltip if no subscores

---

Website-and-Backend/src/main/java/com/example/appengine/springboot/Business.java
Website-and-Backend/src/main/java/com/example/appengine/springboot/SpringbootApplication.java
Website-and-Backend/src/main/resources/Top 50 Online Retailers & Manual Scores - Sheet1.csv

@CubeOfCheese 
- Updated Top 50 data 
- Added .socialScore to Business
- Updated searchDataSource to account for .socialScore

50 top update

---

Website-and-Backend/src/main/resources/public/stylescripts/script.js

Put color changing into functions and adjusted for window widths

Fixed menu colors

---

Extension/popup.html
Extension/popup.js
Extension/stylesheets/stylesheet.css

Rounded subratings to nearest 10th digit and also adjusted spacing

Rounded subratings

---

Website-and-Backend/src/main/resources/public/faq.html
Website-and-Backend/src/main/resources/public/index.html
Website-and-Backend/src/main/resources/public/stylescripts/script.js
Website-and-Backend/src/main/resources/public/stylescripts/style.css

Added browserextension.dev to News
Adjusted styling and spacing. Added spaces in CSS for formatting. 
Updated article heading sizes of articles:
News Section is still hidden, but when not hidden it looks like this:

Added browserextension.dev to News

---

Website-and-Backend/src/main/resources/public/404.html
Website-and-Backend/src/main/resources/public/faq.html
Website-and-Backend/src/main/resources/public/index.html
Website-and-Backend/src/main/resources/public/privacy.html
Website-and-Backend/src/main/resources/public/stylescripts/script.js
Website-and-Backend/src/main/resources/public/stylescripts/style.css

Remove espanol

---

Extension/manifest.json
Website-and-Backend/pom.xml

Updates version number

---

Website-and-Backend/src/main/resources/public/info.js
Website-and-Backend/src/main/resources/templates/info.html

Hides green power text when no percentage is available

---

.gitignore
Extension/popup.html
Extension/popup.js

No visual changes. Just removed all `something.innerHTML = blah;` instances in the extension to conform to Firefox's standards.
Also added *.zip to .gitignore because we have to make zip files when uploading updates and don't want to accidentally add that the repo cuz it's unneccessary

Firefox patch

---

Extension/background.js
Extension/images/menu.svg
Extension/manifest.json
Extension/popup.js
Extension/popupNoRating.html
Extension/popupOptin.html
Extension/popupOptin.js
Extension/stylesheets/stylesheet.css

- Added popupOptin.html - displayed for one time when user installs extension
- Added popupOptin.js - closes windows when user clicks button
- Changed Background.js for chrome.storage.local.get
- Added some styling and animation
- Changed menu icon color
- Fixed minor hover bug (when scores aren't displayed)

Add opt in

---

Extension/popup.html
Extension/popup.js
Extension/popupNotShop.html
Extension/stylesheets/stylesheet.css

Added social score and changed styling

Add social score

---

Extension/background.js

Fixed bug that wasn't displaying any popup on blacklisted sites

Fixes typo and styling

---

Extension/manifest.json

update extension version number

---

Website-and-Backend/src/main/resources/public/stylescripts/script.js
Website-and-Backend/src/main/resources/public/stylescripts/style.css
Website-and-Backend/src/main/resources/templates/index.html

Added submenu when "Extension" is clicked in the menu.
Updated Styling
Fixed toggle bug in script.js

Added submenu

---

Extension/background.js
Extension/popup.js

This will fix name identification for some websites

adds docs. and us. to url prefixes. Moves into a function for organization.

---

Website-and-Backend/src/main/resources/public/info.js
Website-and-Backend/src/main/resources/public/stylescripts/info-script.js
Website-and-Backend/src/main/resources/public/stylescripts/info-style.css
Website-and-Backend/src/main/resources/templates/info.html

Added Animal Content that displays conditionally

Add animal content

---

Extension/background.js

No longer has hard coded checks for www. docs. and us., instead it just looks for the second to last occurrence of a period and cuts everything before that
Closes #285

Changes url parsing algo to omit all url subdomains

---

Extension/popup.js
Extension/popupNoRating.html
Extension/stylesheets/stylesheet-norating.css
Extension/stylesheets/stylesheet.css

Fixes errors that were preventing badges from displaying when there is no rating

---

Extension/manifest.json
Website-and-Backend/pom.xml

Update version number

---

Extension/content.js
Extension/popup.js

Fixed ad window height

---

Website-and-Backend/src/main/resources/public/stylescripts/script.js
Website-and-Backend/src/main/resources/public/stylescripts/style.css
Website-and-Backend/src/main/resources/templates/faq.html
Website-and-Backend/src/main/resources/templates/index.html

Website and faq update

---

README.md

Published Website
